### ISSUE TITLE
Staking contract

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#15]
Good Staking PRD
https://docs.google.com/document/d/1TEACKBwEhNFAglk_g1vZJKvOxZSpprbH7_nOTtloF-w/edit#

- [ ] generic staking contract
- [ ] generic staking contract should issue an LP token
     - multiplier is reset on transfer
     - rewards are minted on transfer
- [ ] fund manager should hold list of whitelisted staking contracts
- [ ] fund manager should be able to modify whitelisted staking contract reward rate
- [ ] fund manager should iteratively while have gas collect interest starting with contract with most interest
- [ ] generic staking contract should calculate rewards for stakers
   - by current block reward rate
   - multiplier 2x after 1 month

**Comment by tomerGD** [comment]
https://docs.google.com/document/d/1TEACKBwEhNFAglk_g1vZJKvOxZSpprbH7_nOTtloF-w/edit#
