### ISSUE TITLE
Upgrade process script

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#19]
- [ ] design process (announcment, timings etc)
- [ ] nameservice - deployed with correct addresses (BANCOR_FORMULA)
- [ ] avatar.nativeToken() ???? remove usage in contracts.
- [ ] reputation airdrop
- [ ] gdx airdrop
- [x] gdao distribution contracts should have minting permissions (via nameService)
- [x] avatar should own contracts (reserve, token etc..)
- [ ] add new contracts to Identity so they do not pay future TX fees
- [x] GoodReserve 
    - with 2.2T limit. 
    - make minter
    - renounce minter from avatar
    - add as GlobalConstraint for mintTokens
    - transfer locked comp to Avatar
    - end reserve 
    - transfer cdai to new reserve
    - initialize new reserve with correct RR and price (cdai/g$)
- [x] governance
      - unregister old gov
      - register new compoundvoting machine
- [ ] SimpleStaking
   - end
   - move etoro and foundation funds to new staking contract
   - deploy new staking contracts
- [ ] ubischeme
  - move funds from old scheme and end it
  - start new scheme
  - should work with claimersdistribution
- [ ] donation staking -move donations to new staking contract
