### ISSUE TITLE
Fuse staking for G$ rewards

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#208]
Upgrade current FuseStaking contract
- [x] stakers should get gFuse tokens
- [x] staker should be able to choose `giveBackRatio` to DAO (out of his rewards, min 10% - parameter)
   - notice you need to keep an average of donated ratio globally and per staker
   - notice when transferring tokens, the donation ratio for received tokens will be the same as the current receiver average
- [x] suggest and implement solution fuse staking is locked for 7 days
    - withdraw buffer or triple withdraw (submit intent, withdraw all daily intents, after 7 days withdraw your stake)
    - other?
- [ ] collect rewards and calculate DAO part(ie give back ratio) vs stakers part
   - DAO part, according to cap/minimum, should go to: fusefaucet (fuse), firstclaim (gd), invite pool(gd), UBI (gd), community pool (gd)
   - stakers part (gd)
- [ ] DAO part target distribution - how much should be sent to fusefaucet/firstclaimpool/invitepool
   - fusefaucet, firstclaim, invitepool - calculate spending rate (current balance vs previous recorded balance). should have `reservePeriodDays`(default 1 week) of spending at current rate. if below target balance then send enough to cover last epoch spent amount + `reserveTopExtra` (default 10%).
    *notice fusefaucet is in FUSE tokens while firstclaim/invite are GD*
   - UBI/Community pool - split according to set percentages
- [x] define guardian role - on top of Avatar - able to pause, set `reservePeriodDays`, ubi/community percentages, min `giveBackRatio`
